# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProfileMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProfileMessage.proto',
  package='LLVM.TDG',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ProfileMessage.proto\x12\x08LLVM.TDG\"|\n\x0f\x46unctionProfile\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\x12/\n\x03\x62\x62s\x18\x02 \x03(\x0b\x32\".LLVM.TDG.FunctionProfile.BbsEntry\x1a*\n\x08\x42\x62sEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"\xc9\x01\n\x08Interval\x12\x10\n\x08inst_lhs\x18\x01 \x01(\x04\x12\x10\n\x08inst_rhs\x18\x02 \x01(\x04\x12\x10\n\x08mark_lhs\x18\x03 \x01(\x04\x12\x10\n\x08mark_rhs\x18\x04 \x01(\x04\x12,\n\x05\x66uncs\x18\x05 \x03(\x0b\x32\x1d.LLVM.TDG.Interval.FuncsEntry\x1aG\n\nFuncsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.LLVM.TDG.FunctionProfile:\x02\x38\x01\"\xb4\x01\n\x07Profile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x05\x66uncs\x18\x02 \x03(\x0b\x32\x1c.LLVM.TDG.Profile.FuncsEntry\x12%\n\tintervals\x18\x03 \x03(\x0b\x32\x12.LLVM.TDG.Interval\x1aG\n\nFuncsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.LLVM.TDG.FunctionProfile:\x02\x38\x01\x62\x06proto3'
)




_FUNCTIONPROFILE_BBSENTRY = _descriptor.Descriptor(
  name='BbsEntry',
  full_name='LLVM.TDG.FunctionProfile.BbsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='LLVM.TDG.FunctionProfile.BbsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='LLVM.TDG.FunctionProfile.BbsEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=158,
)

_FUNCTIONPROFILE = _descriptor.Descriptor(
  name='FunctionProfile',
  full_name='LLVM.TDG.FunctionProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='func', full_name='LLVM.TDG.FunctionProfile.func', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bbs', full_name='LLVM.TDG.FunctionProfile.bbs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FUNCTIONPROFILE_BBSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=158,
)


_INTERVAL_FUNCSENTRY = _descriptor.Descriptor(
  name='FuncsEntry',
  full_name='LLVM.TDG.Interval.FuncsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='LLVM.TDG.Interval.FuncsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='LLVM.TDG.Interval.FuncsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=362,
)

_INTERVAL = _descriptor.Descriptor(
  name='Interval',
  full_name='LLVM.TDG.Interval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inst_lhs', full_name='LLVM.TDG.Interval.inst_lhs', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inst_rhs', full_name='LLVM.TDG.Interval.inst_rhs', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mark_lhs', full_name='LLVM.TDG.Interval.mark_lhs', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mark_rhs', full_name='LLVM.TDG.Interval.mark_rhs', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funcs', full_name='LLVM.TDG.Interval.funcs', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INTERVAL_FUNCSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=362,
)


_PROFILE_FUNCSENTRY = _descriptor.Descriptor(
  name='FuncsEntry',
  full_name='LLVM.TDG.Profile.FuncsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='LLVM.TDG.Profile.FuncsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='LLVM.TDG.Profile.FuncsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=362,
)

_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='LLVM.TDG.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LLVM.TDG.Profile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funcs', full_name='LLVM.TDG.Profile.funcs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intervals', full_name='LLVM.TDG.Profile.intervals', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROFILE_FUNCSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=545,
)

_FUNCTIONPROFILE_BBSENTRY.containing_type = _FUNCTIONPROFILE
_FUNCTIONPROFILE.fields_by_name['bbs'].message_type = _FUNCTIONPROFILE_BBSENTRY
_INTERVAL_FUNCSENTRY.fields_by_name['value'].message_type = _FUNCTIONPROFILE
_INTERVAL_FUNCSENTRY.containing_type = _INTERVAL
_INTERVAL.fields_by_name['funcs'].message_type = _INTERVAL_FUNCSENTRY
_PROFILE_FUNCSENTRY.fields_by_name['value'].message_type = _FUNCTIONPROFILE
_PROFILE_FUNCSENTRY.containing_type = _PROFILE
_PROFILE.fields_by_name['funcs'].message_type = _PROFILE_FUNCSENTRY
_PROFILE.fields_by_name['intervals'].message_type = _INTERVAL
DESCRIPTOR.message_types_by_name['FunctionProfile'] = _FUNCTIONPROFILE
DESCRIPTOR.message_types_by_name['Interval'] = _INTERVAL
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FunctionProfile = _reflection.GeneratedProtocolMessageType('FunctionProfile', (_message.Message,), {

  'BbsEntry' : _reflection.GeneratedProtocolMessageType('BbsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FUNCTIONPROFILE_BBSENTRY,
    '__module__' : 'ProfileMessage_pb2'
    # @@protoc_insertion_point(class_scope:LLVM.TDG.FunctionProfile.BbsEntry)
    })
  ,
  'DESCRIPTOR' : _FUNCTIONPROFILE,
  '__module__' : 'ProfileMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.FunctionProfile)
  })
_sym_db.RegisterMessage(FunctionProfile)
_sym_db.RegisterMessage(FunctionProfile.BbsEntry)

Interval = _reflection.GeneratedProtocolMessageType('Interval', (_message.Message,), {

  'FuncsEntry' : _reflection.GeneratedProtocolMessageType('FuncsEntry', (_message.Message,), {
    'DESCRIPTOR' : _INTERVAL_FUNCSENTRY,
    '__module__' : 'ProfileMessage_pb2'
    # @@protoc_insertion_point(class_scope:LLVM.TDG.Interval.FuncsEntry)
    })
  ,
  'DESCRIPTOR' : _INTERVAL,
  '__module__' : 'ProfileMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.Interval)
  })
_sym_db.RegisterMessage(Interval)
_sym_db.RegisterMessage(Interval.FuncsEntry)

Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), {

  'FuncsEntry' : _reflection.GeneratedProtocolMessageType('FuncsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROFILE_FUNCSENTRY,
    '__module__' : 'ProfileMessage_pb2'
    # @@protoc_insertion_point(class_scope:LLVM.TDG.Profile.FuncsEntry)
    })
  ,
  'DESCRIPTOR' : _PROFILE,
  '__module__' : 'ProfileMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.Profile)
  })
_sym_db.RegisterMessage(Profile)
_sym_db.RegisterMessage(Profile.FuncsEntry)


_FUNCTIONPROFILE_BBSENTRY._options = None
_INTERVAL_FUNCSENTRY._options = None
_PROFILE_FUNCSENTRY._options = None
# @@protoc_insertion_point(module_scope)
