# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TraceMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TraceMessage.proto',
  package='LLVM.TDG',
  syntax='proto3',
  serialized_pb=_b('\n\x12TraceMessage.proto\x12\x08LLVM.TDG\"?\n\x10\x44ynamicLLVMValue\x12\x0f\n\x05v_int\x18\x01 \x01(\x04H\x00\x12\x11\n\x07v_bytes\x18\x02 \x01(\x0cH\x00\x42\x07\n\x05value\"}\n\x16\x44ynamicLLVMInstruction\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12*\n\x06params\x18\x02 \x03(\x0b\x32\x1a.LLVM.TDG.DynamicLLVMValue\x12*\n\x06result\x18\x03 \x01(\x0b\x32\x1a.LLVM.TDG.DynamicLLVMValue\"T\n\x18\x44ynamicLLVMFunctionEnter\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\x12*\n\x06params\x18\x02 \x03(\x0b\x32\x1a.LLVM.TDG.DynamicLLVMValue\"\x8c\x01\n\x15\x44ynamicLLVMTraceEntry\x12\x30\n\x04inst\x18\x01 \x01(\x0b\x32 .LLVM.TDG.DynamicLLVMInstructionH\x00\x12\x38\n\nfunc_enter\x18\x02 \x01(\x0b\x32\".LLVM.TDG.DynamicLLVMFunctionEnterH\x00\x42\x07\n\x05\x45ntryb\x06proto3')
)




_DYNAMICLLVMVALUE = _descriptor.Descriptor(
  name='DynamicLLVMValue',
  full_name='LLVM.TDG.DynamicLLVMValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v_int', full_name='LLVM.TDG.DynamicLLVMValue.v_int', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_bytes', full_name='LLVM.TDG.DynamicLLVMValue.v_bytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='LLVM.TDG.DynamicLLVMValue.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=95,
)


_DYNAMICLLVMINSTRUCTION = _descriptor.Descriptor(
  name='DynamicLLVMInstruction',
  full_name='LLVM.TDG.DynamicLLVMInstruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='LLVM.TDG.DynamicLLVMInstruction.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='LLVM.TDG.DynamicLLVMInstruction.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='LLVM.TDG.DynamicLLVMInstruction.result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=222,
)


_DYNAMICLLVMFUNCTIONENTER = _descriptor.Descriptor(
  name='DynamicLLVMFunctionEnter',
  full_name='LLVM.TDG.DynamicLLVMFunctionEnter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='func', full_name='LLVM.TDG.DynamicLLVMFunctionEnter.func', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='LLVM.TDG.DynamicLLVMFunctionEnter.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=308,
)


_DYNAMICLLVMTRACEENTRY = _descriptor.Descriptor(
  name='DynamicLLVMTraceEntry',
  full_name='LLVM.TDG.DynamicLLVMTraceEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inst', full_name='LLVM.TDG.DynamicLLVMTraceEntry.inst', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='func_enter', full_name='LLVM.TDG.DynamicLLVMTraceEntry.func_enter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Entry', full_name='LLVM.TDG.DynamicLLVMTraceEntry.Entry',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=311,
  serialized_end=451,
)

_DYNAMICLLVMVALUE.oneofs_by_name['value'].fields.append(
  _DYNAMICLLVMVALUE.fields_by_name['v_int'])
_DYNAMICLLVMVALUE.fields_by_name['v_int'].containing_oneof = _DYNAMICLLVMVALUE.oneofs_by_name['value']
_DYNAMICLLVMVALUE.oneofs_by_name['value'].fields.append(
  _DYNAMICLLVMVALUE.fields_by_name['v_bytes'])
_DYNAMICLLVMVALUE.fields_by_name['v_bytes'].containing_oneof = _DYNAMICLLVMVALUE.oneofs_by_name['value']
_DYNAMICLLVMINSTRUCTION.fields_by_name['params'].message_type = _DYNAMICLLVMVALUE
_DYNAMICLLVMINSTRUCTION.fields_by_name['result'].message_type = _DYNAMICLLVMVALUE
_DYNAMICLLVMFUNCTIONENTER.fields_by_name['params'].message_type = _DYNAMICLLVMVALUE
_DYNAMICLLVMTRACEENTRY.fields_by_name['inst'].message_type = _DYNAMICLLVMINSTRUCTION
_DYNAMICLLVMTRACEENTRY.fields_by_name['func_enter'].message_type = _DYNAMICLLVMFUNCTIONENTER
_DYNAMICLLVMTRACEENTRY.oneofs_by_name['Entry'].fields.append(
  _DYNAMICLLVMTRACEENTRY.fields_by_name['inst'])
_DYNAMICLLVMTRACEENTRY.fields_by_name['inst'].containing_oneof = _DYNAMICLLVMTRACEENTRY.oneofs_by_name['Entry']
_DYNAMICLLVMTRACEENTRY.oneofs_by_name['Entry'].fields.append(
  _DYNAMICLLVMTRACEENTRY.fields_by_name['func_enter'])
_DYNAMICLLVMTRACEENTRY.fields_by_name['func_enter'].containing_oneof = _DYNAMICLLVMTRACEENTRY.oneofs_by_name['Entry']
DESCRIPTOR.message_types_by_name['DynamicLLVMValue'] = _DYNAMICLLVMVALUE
DESCRIPTOR.message_types_by_name['DynamicLLVMInstruction'] = _DYNAMICLLVMINSTRUCTION
DESCRIPTOR.message_types_by_name['DynamicLLVMFunctionEnter'] = _DYNAMICLLVMFUNCTIONENTER
DESCRIPTOR.message_types_by_name['DynamicLLVMTraceEntry'] = _DYNAMICLLVMTRACEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DynamicLLVMValue = _reflection.GeneratedProtocolMessageType('DynamicLLVMValue', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICLLVMVALUE,
  __module__ = 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.DynamicLLVMValue)
  ))
_sym_db.RegisterMessage(DynamicLLVMValue)

DynamicLLVMInstruction = _reflection.GeneratedProtocolMessageType('DynamicLLVMInstruction', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICLLVMINSTRUCTION,
  __module__ = 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.DynamicLLVMInstruction)
  ))
_sym_db.RegisterMessage(DynamicLLVMInstruction)

DynamicLLVMFunctionEnter = _reflection.GeneratedProtocolMessageType('DynamicLLVMFunctionEnter', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICLLVMFUNCTIONENTER,
  __module__ = 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.DynamicLLVMFunctionEnter)
  ))
_sym_db.RegisterMessage(DynamicLLVMFunctionEnter)

DynamicLLVMTraceEntry = _reflection.GeneratedProtocolMessageType('DynamicLLVMTraceEntry', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICLLVMTRACEENTRY,
  __module__ = 'TraceMessage_pb2'
  # @@protoc_insertion_point(class_scope:LLVM.TDG.DynamicLLVMTraceEntry)
  ))
_sym_db.RegisterMessage(DynamicLLVMTraceEntry)


# @@protoc_insertion_point(module_scope)
