# Includer should define
# $ROOT_DIR
# $ALL_SRCS
# $INCLUDE_DIR
# $CFLAGS
# $KERN
# $LINK_FLAG

PASS_SO_DIR=${ROOT_DIR}/build/prototype
OPT_ARGS=-load=$(PASS_SO_DIR)/libPrototypePass.so -S -time-passes

LLVMS=$(ALL_SRCS:%.c=%.o)
LLVM_TRACES=$(LLVMS:%.ll=%.tll)
LLVM_REPLAYS=$(LLVMS:%.ll=%.rll)

TRACE_LINK_FLAGS="${LINK_FLAG} -lz"

# Compile
%.o: %.c
	clang -flto -I${INCLUDE_DIR} ${CFLAGS} -o $@ -c $^

$(KERN).bc: $(LLVMS)
	clang -flto -Wl,-plugin-opt=emit-llvm $^ -o $@
	# Name everthing
	opt -instnamer $@ -o $@

# Instrument
$(KERN)_trace.ll: $(KERN).bc
	opt $(OPT_ARGS) -debug-only=PrototypePass -prototype -o $@ $^

$(KERN)_replay.ll: $(KERN).bc
	opt $(OPT_ARGS) -debug-only=ReplayPass,DynamicTrace -replay -trace-file=llvm_trace.gz $^ -o $@ 

# To binary.
$(KERN)_trace: $(KERN)_trace.ll $(ROOT_DIR)/prototype/logger.c
	clang -O0 $^ -o $@ ${TRACE_LINK_FLAGS}

$(KERN)_replay: $(KERN)_replay.ll ../../../replay.c
	clang -O0 $^ -o $@ ${LINK_FLAG}

run_trace: $(KERN)_trace input.data check.data
	./$(KERN)_trace input.data check.data

clean_trace:
	rm -f $(KERN)_trace $(LLVMS) $(LLVM_TRACES) $(KERN)_trace.bc $(KERN)_trace.s

clean_replay:
	rm -f $(KERN)_replay $(LLVMS) $(LLVM_REPLAYS) $(KERN)_replay.bc $(KERN)_replay.s
